### ISSUE TITLE
案件探しサイトの紹介ページ

### ISSUE THREAD

**Issue by sekitaka** [lachelier/freelance#3]
# why
* 案件探しに役立つといいな
* 実際の利用者の声があると参考になるな
* Slackでの情報 https://commew.slack.com/archives/C9F92VCKW/p1624875407314200

**Comment by muchoco-dev** [comment]
わーい
issueありがとうございますー！案件あってのフリーランスですもんね！！

案件探しサイト = エージェントやクラウドソーシングサービスの認識であってますか？

**Comment by sekitaka** [comment]
@lachelier そうです〜。
エージェントやクラウドソーシングとかですー

**Comment by muchoco-dev** [comment]
対応しました！
#5 #6

**Comment by sekitaka** [comment]
@lachelier わわ！ありがとうございます！

**Comment by sekitaka** [comment]
ランサーズトップってもう無いのかな 🤔

**Comment by muchoco-dev** [comment]
@sekitaka 
たぶんURLが https://lancerstop.jp/ だと思うんですけど、アクセスできなくなってました＞＜
