### ISSUE TITLE
掲示板ページ

### ISSUE THREAD

**Issue by Naoki0722** [lachelier/freelance#4]
お役立ち情報などをフリーランスの人同士で交流しながらワイワイ言い合えるようなページがあるといいな

**Comment by muchoco-dev** [comment]
issue ありがとうございますー！
なるほど掲示板！！みんなでわいわいしたいですね🙌
ただ、現状デプロイ先が GitHub Pages なので、 PHP とかは動かせなくて、、、＞＜

たとえば commew の Slack でわいわい話した内容をこっちに移植するとかはどうでしょう？

**Comment by Naoki0722** [comment]
@lachelier 

そうなんですよね、、、あったらいいなで挙げさせてもらいました。。。！

> たとえば commew の Slack でわいわい話した内容をこっちに移植するとかはどうでしょう？

たしかにそういうので雰囲気作るのもいいかもしれません！
